version: "3"

services:
  minecraft:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      RCON_CMDS_STARTUP: |-
        gamerule keepInventory true
        gamerule lavaSourceConversion true
    volumes:
      # attach the relative directory 'data' to the container's /data path
      - "${docker_data_folder}/minecraft:/config"
